apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: todo-app
type: Opaque
stringData:
  JWT_SECRET: 14b62f73d0eea4d1b90d1c01a511d4103d616ec083cdb5a0328db14b3895463ccc9d7fdb26d8081625d9b234ee0ea18eba1f1adba36b01af706b42c85d2fb8ee

# Notes:
# - Secret is used for sensitive values such as JWT_SECRET, passwords, API keys.
# - stringData lets you write plain text here; Kubernetes converts it to base64.
# - In real projects, do not commit real secrets to GitHub.
# - Later, if MongoDB uses username/password, put those values in Secret too.
