apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:7
          ports:
            - containerPort: 27017
          envFrom:
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc

# Notes:
# - MongoDB should have 1 replica for this learning project.
# - The pod label is app: mongodb. The MongoDB Service will use this selector.
# - mongo:7 is the official MongoDB image.
# - containerPort 27017 is MongoDB's default port.
# - envFrom loads MongoDB username/password from mongo-secret.
# - /data/db is where MongoDB stores database files inside the container.
# - The PVC keeps data safe if the MongoDB pod is deleted and recreated.
